name: linting-workflow
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install html hint
        run: npm install --save-dev htmlhint
      - name: Lint HTML Files
        run: npx htmlhint "**/*.html"
      - name: Install Style lint
        run: npm install --save-dev stylelint
      - name: Lint CSS Files
        run: npx stylelint "**/*.css"
